<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
    <line>
      <![CDATA[Negative Case Number: 01]]>
    </line>
    <line>
      <![CDATA[Excepted: Same as password entered before]]>
    </line>
    <line>
      <![CDATA[Actual: Not same password]]>
    </line>
    <line>
      <![CDATA[Status: Failed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="44336" started-at="2020-02-11T10:34:34 EST" finished-at="2020-02-11T10:35:18 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44336" started-at="2020-02-11T10:34:34 EST" finished-at="2020-02-11T10:35:18 EST">
      <class name="TestDemo.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:TestDemo.NewTest@3891771e]" name="beforeTest" is-config="true" duration-ms="3960" started-at="2020-02-11T10:34:34 EST" finished-at="2020-02-11T10:34:38 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="negative()[pri:1, instance:TestDemo.NewTest@3891771e]" name="negative" duration-ms="6087" started-at="2020-02-11T10:34:38 EST" description="My Test Fail" finished-at="2020-02-11T10:34:44 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Amazon Registration expected:<Amazon Registration> but was:<Negative Case>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Amazon Registration expected:<Amazon Registration> but was:<Negative Case>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at TestDemo.NewTest.negative(NewTest.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Negative Case Number: 01]]>
            </line>
            <line>
              <![CDATA[Excepted: Same as password entered before]]>
            </line>
            <line>
              <![CDATA[Actual: Not same password]]>
            </line>
            <line>
              <![CDATA[Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- negative -->
        <test-method status="PASS" signature="positive()[pri:2, instance:TestDemo.NewTest@3891771e]" name="positive" duration-ms="11488" started-at="2020-02-11T10:34:44 EST" description="My Test Successful" finished-at="2020-02-11T10:34:55 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positive -->
        <test-method status="PASS" signature="login()[pri:3, instance:TestDemo.NewTest@3891771e]" name="login" duration-ms="9345" started-at="2020-02-11T10:34:55 EST" finished-at="2020-02-11T10:35:05 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="addItemsToCart()[pri:4, instance:TestDemo.NewTest@3891771e]" name="addItemsToCart" duration-ms="13285" started-at="2020-02-11T10:35:05 EST" finished-at="2020-02-11T10:35:18 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addItemsToCart -->
      </class> <!-- TestDemo.NewTest -->
      <class name="TestDemo.AppTest">
        <test-method status="PASS" signature="shouldAnswerWithTrue()[pri:0, instance:TestDemo.AppTest@78ac1102]" name="shouldAnswerWithTrue" duration-ms="2" started-at="2020-02-11T10:35:18 EST" finished-at="2020-02-11T10:35:18 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldAnswerWithTrue -->
      </class> <!-- TestDemo.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
